version: "3.3"

services:
  web:
    build: .
    environment:
      PORT: 8080
      JDBC_URL: "jdbc:postgresql://db:5432"
      DATABASE: personia
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: secret
      JWT_ISSUER: "http://0.0.0.0:8080/"
      JWT_AUDIENCE: "http://0.0.0.0:8080/hierarchy"
      JWT_REALM: "Access to 'hierarchy'"
      JWT_EXPIRATION: 31536000
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: personia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s