version: "3.3"

services:
  web:
    build: .
    environment:
      PORT: ${WEB_PORT}
      JDBC_URL: ${WEB_DB_URL}
      DATABASE: ${WEB_DATABASE}
      DB_USERNAME: ${WEB_DB_USERNAME}
      DB_PASSWORD: ${WEB_DB_PASSWORD}
      JWT_SECRET: secret
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_REALM: ${JWT_REALM}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${WEB_DATABASE}
      POSTGRES_USER: ${WEB_DB_USERNAME}
      POSTGRES_PASSWORD: ${WEB_DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s